groups:
  - name: project-manager-alerts
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # Low disk space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

      # Application down
      - alert: ApplicationDown
        expr: up{job=~"backend|frontend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Application is down"
          description: "{{ $labels.job }} application is down on {{ $labels.instance }}"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time"
          description: "95th percentile response time is above 500ms for {{ $labels.job }}"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "Error rate is above 5% for {{ $labels.job }}"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: postgres_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection issues"
          description: "Cannot connect to PostgreSQL database"

      # High database connections
      - alert: HighDatabaseConnections
        expr: postgres_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "PostgreSQL has {{ $value }} active connections"

      # Container restart
      - alert: ContainerRestart
        expr: increase(container_start_time_seconds[10m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container restarted"
          description: "Container {{ $labels.name }} has restarted"

      # High container memory usage
      - alert: HighContainerMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High container memory usage"
          description: "Container {{ $labels.name }} memory usage is above 90%"

  - name: ssl-certificate-alerts
    rules:
      # SSL certificate expiry
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate will expire soon"
          description: "SSL certificate for {{ $labels.instance }} will expire in less than 30 days"

      # SSL certificate critical expiry
      - alert: SSLCertificateCriticalExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate will expire very soon"
          description: "SSL certificate for {{ $labels.instance }} will expire in less than 7 days"

  - name: deployment-alerts
    rules:
      # Deployment failure
      - alert: DeploymentFailure
        expr: increase(deployment_failures_total[10m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Deployment failure detected"
          description: "Deployment has failed for {{ $labels.environment }}"

      # Rollback occurred
      - alert: RollbackOccurred
        expr: increase(deployment_rollbacks_total[10m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Deployment rollback occurred"
          description: "Rollback has occurred for {{ $labels.environment }}" 