name: Test Simple

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Simple test
        run: |
          echo "Hello from GitHub Actions!"
          echo "Current directory: $(pwd)"
          echo "Files in repo:"
          ls -la
          
      - name: Test summary
        run: |
          echo "## Simple Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ GitHub Actions is working!" >> $GITHUB_STEP_SUMMARY 