name: Simple Test Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  simple-test:
    name: Simple Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Test Go installation
        run: go version
        
      - name: Run backend tests
        run: |
          cd backend
          go test -v -short ./...
        continue-on-error: true
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Test Node installation
        run: node --version
        
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
        continue-on-error: true
        
      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watchAll=false --passWithNoTests
        continue-on-error: true 